# site
site_name: Wenrui Huang's Homepage
site_description: The main personal page for Wenrui Huang（黄文睿).
site_author: Wenrui Huang(黄文睿)
site_url: https://rijuyuezhu.top


nav:
  - 'index.md'
  - Projects:
    - 'projects/20222-webmake-lc.md'
  - Blogs: 'https://blog.rijuyuezhu.top'


theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: True

plugins: []
