# project info
site_name: Wenrui Huang's Homepage
site_description: The main personal page for Wenrui Huang（黄文睿).
site_author: Wenrui Huang(黄文睿)
site_url: https://rijuyuezhu.top

# copyright
copyright: Copyright &copy; 2023-present Wenrui Huang

# page tree
nav:
  - 'index.md'
  - Projects:
    - 'projects/index.md'
    - 'projects/20222-webmake-lc.md'
  - Blog: 'https://blog.rijuyuezhu.top'


# theme configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    text: Georgia
    code: Consolas

# extensions
markdown_extensions:
  - toc:
      permalink: True

# plugins
plugins: [] # no search
