# site
site_name: Wenrui Huang's Main Page
site_description: The main personal page for Wenrui Huang（黄文睿).
site_author: Wenrui Huang(黄文睿)
site_url: https://rijuyuezhu.top

# repo
repo_name: 'rijuyuezhu/main-page'
repo_url: 'https://github.com/rijuyuezhu/main-page'

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Home: 'index.md'
  - Projects: 'https://project.rijuyuezhu.top'
  - Blogs: 'https://blog.rijuyuezhu.top'


markdown_extensions:
  - toc:
      permalink: "#"
